(async()=>{try{const i=await browser.runtime.getBrowserInfo();if(i?.name&&i.name.toLowerCase().includes('thunderbird')){document.body.innerHTML=`<main style="padding:12px;font:14px system-ui"><h3>Ask a Fox ToolKit</h3><p>This build is for <strong>Firefox</strong>. You’re running <strong>Thunderbird</strong>, so the fix tools aren’t available here.</p><p>If you want Thunderbird helpers, use StormWall / the TB add-on instead.</p></main>`;throw new Error('TB host guard');}}catch(e){if(e.message==='TB host guard'){throw e;}}})();
const tabs=document.querySelectorAll('.tabs button');const sections={fixes:document.getElementById('tab-fixes'),volunteer:document.getElementById('tab-volunteer'),tb:document.getElementById('tab-tb')};
tabs.forEach(btn=>btn.addEventListener('click',()=>{tabs.forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false');b.tabIndex=-1;});btn.classList.add('active');btn.setAttribute('aria-selected','true');btn.tabIndex=0;Object.values(sections).forEach(s=>s.classList.remove('active'));const k=btn.dataset.tab;sections[k].classList.add('active');}));
document.querySelector('.tabs').addEventListener('keydown',e=>{const order=[...document.querySelectorAll('.tabs [role="tab"]')];const i=order.indexOf(document.activeElement);if(e.key==='ArrowRight'){order[(i+1)%order.length].focus();e.preventDefault();}if(e.key==='ArrowLeft'){order[(i-1+order.length)%order.length].focus();e.preventDefault();}});
document.getElementById('go-tb')?.addEventListener('click',e=>{e.preventDefault();document.querySelector('.tabs button[data-tab="tb"]').click();});
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800);}function afterFixCTA(){if(!sessionStorage.getItem('ctaShown')){toast('Thanks for helping Firefox! Press Alt+3 to learn about Thunderbird.');sessionStorage.setItem('ctaShown','1');}}
document.addEventListener('keydown',e=>{if(e.altKey&&e.key==='1')document.querySelector('.tabs button[data-tab="fixes"]').click();if(e.altKey&&e.key==='2')document.querySelector('.tabs button[data-tab="volunteer"]').click();if(e.altKey&&e.key==='3')document.querySelector('.tabs button[data-tab="tb"]').click();if(e.altKey&&(e.key==='s'||e.key==='S'))document.getElementById('btn-screenshot')?.click();});
const kpiEls={fixes:document.getElementById('kpi-fixes'),shots:document.getElementById('kpi-shots'),templates:document.getElementById('kpi-templates'),tb:document.getElementById('kpi-tb')};
async function loadCounters(){const{aafCounters={fixes:0,shots:0,templates:0,tb:0}}=await browser.storage.local.get('aafCounters');updateKPI('fixes',aafCounters.fixes);updateKPI('shots',aafCounters.shots);updateKPI('templates',aafCounters.templates);updateKPI('tb',aafCounters.tb);}function bump(el){if(!el)return;el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump');}
async function incCounter(key){const store=await browser.storage.local.get('aafCounters');const c=store.aafCounters||{fixes:0,shots:0,templates:0,tb:0};c[key]=(c[key]||0)+1;await browser.storage.local.set({aafCounters:c});updateKPI(key,c[key]);}function updateKPI(key,val){const el=kpiEls[key];if(el){el.textContent=String(val);bump(el);}}
loadCounters();
document.getElementById('btn-reload')?.addEventListener('click',async()=>{const[tab]=await browser.tabs.query({active:true,currentWindow:true});if(tab?.id)await browser.tabs.reload(tab.id,{bypassCache:true});toast('Reloaded without cache');afterFixCTA();incCounter('fixes');});
document.getElementById('btn-about-support')?.addEventListener('click',async()=>{await browser.tabs.create({url:'about:support'});toast('Opened about:support');});
document.getElementById('btn-about-profiles')?.addEventListener('click',async()=>{await browser.tabs.create({url:'about:profiles'});toast('Opened about:profiles');});
document.getElementById('btn-copy-env')?.addEventListener('click',async()=>{const info=await browser.runtime.getBrowserInfo();const plat=await browser.runtime.getPlatformInfo();const lines=[`App: ${info.name} ${info.version}`,`Platform: ${plat.os} ${plat.arch}`,`UA: ${navigator.userAgent}`];try{await navigator.clipboard.writeText(lines.join('\n'));toast('Environment copied');afterFixCTA();incCounter('fixes');}catch{}});
document.getElementById('btn-screenshot')?.addEventListener('click',async()=>{try{const dataUrl=await browser.tabs.captureVisibleTab();const now=new Date().toISOString().replace(/[:.]/g,'-');await browser.downloads.download({url:dataUrl,filename:`ask-a-fox/screenshot-${now}.png`,saveAs:true});toast('Screenshot saved');afterFixCTA();incCounter('shots');}catch(e){toast('Screenshot failed');}});
async function clearCacheAll(){try{await browser.browsingData.remove({since:0},{cache:true});toast('Cache cleared');afterFixCTA();incCounter('fixes');}catch(e){toast('Could not clear cache. Try Settings > Privacy & Security.');}}
document.getElementById('btn-clear-cache')?.addEventListener('click',clearCacheAll);
document.getElementById('btn-bug-report')?.addEventListener('click',async()=>{await browser.tabs.create({url:'https://support.mozilla.org/questions/new'});});
async function safeLoad(p,f){try{const r=await fetch(p);if(!r.ok)throw 0;return await r.json();}catch{return f;}}
async function renderVolunteer(){const links=await safeLoad('../data/links.json',{"links":[]});const templates=await safeLoad('../data/templates.json',{"templates":[]});const linksDiv=document.getElementById('links');links.links.forEach(l=>{const a=document.createElement('a');a.href=l.url;a.textContent=l.title;a.target='_blank';linksDiv.appendChild(a);});const tmplDiv=document.getElementById('templates');templates.templates.forEach(t=>{const card=document.createElement('div');card.className='card';const h=document.createElement('h3');h.textContent=t.title;const p=document.createElement('p');p.textContent=t.body;const copyBtn=document.createElement('button');copyBtn.className='btn';copyBtn.textContent='Copy';copyBtn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(t.body);toast('Template copied');incCounter('templates');}catch{}});card.appendChild(h);card.appendChild(p);card.appendChild(copyBtn);tmplDiv.appendChild(card);});document.getElementById('btn-view-dashboard')?.addEventListener('click',()=>{browser.tabs.create({url:'https://lookerstudio.google.com/u/0/reporting/f5d29d7e-6613-41d9-a102-9d9a92036647/page/p_55ncc0jlrd'});});}
async function renderThunderbird(){const guides=await safeLoad('../data/guides.json',{"guides":[]});const container=document.getElementById('tb-preview');const preview=guides.guides.find(g=>g.id==='tb-preview-tab');if(!preview)return;const card=document.createElement('div');card.className='card';const h=document.createElement('h3');h.textContent=preview.title;const p=document.createElement('p');p.textContent=preview.body||'';card.appendChild(h);card.appendChild(p);if(preview.links){const row=document.createElement('div');for(const l of preview.links){const a=document.createElement('a');a.className='btn';a.target='_blank';a.rel='noopener';a.textContent=l.label;a.href='#';a.addEventListener('click',async(e)=>{e.preventDefault();const links=await safeLoad('../data/links.json',{"links":[]});const found=links.links.find(x=>x.id===l.link_id);if(found)browser.tabs.create({url:found.url});});row.appendChild(a);}card.appendChild(row);}container.appendChild(card);}
renderVolunteer();renderThunderbird();
// Share via Google Form (prefilled) + Copy JSON + safeguards
let shareCooldown=false;const DAILY_CAP=2;let tbLast=0;
async function getId(){let{aafClientId}=await browser.storage.local.get('aafClientId');if(!aafClientId){aafClientId=crypto.randomUUID();await browser.storage.local.set({aafClientId});}return aafClientId;}
function fmtDate(d){return new Date(d).toLocaleString();}
async function setLastShared(ts){await browser.storage.local.set({aafLastShared:ts});updateLastShared(ts);}
async function getLastShared(){const{aafLastShared=0}=await browser.storage.local.get('aafLastShared');return aafLastShared;}
function updateLastShared(ts){const el=document.getElementById('last-shared');if(el)el.textContent='Last shared: '+(ts?fmtDate(ts):'never');}
async function getTodayCount(){const{aafShareToday={date:'',count:0}}=await browser.storage.local.get('aafShareToday');const today=new Date().toISOString().slice(0,10);if(aafShareToday.date!==today)return 0;return aafShareToday.count;}
async function bumpTodayCount(){const today=new Date().toISOString().slice(0,10);const c=await getTodayCount();await browser.storage.local.set({aafShareToday:{date:today,count:c+1}});}
async function currentPayload(){const[store,id]=await Promise.all([browser.storage.local.get('aafCounters'),getId()]);const c=store.aafCounters||{fixes:0,shots:0,templates:0,tb:0};return{client_id:id,app:'ask-a-fox-toolkit',app_version:'0.1.3',ts:new Date().toISOString(),fixes:c.fixes,shots:c.shots,templates:c.templates,tb:c.tb};}
function buildPrefillUrl(p){const base='https://docs.google.com/forms/d/e/YOUR_FORM_ID/viewform';const e={client_id:'entry.CLIENT_ID',app:'entry.APP',app_ver:'entry.APP_VERSION',ts:'entry.TIMESTAMP',fixes:'entry.FIXES',shots:'entry.SHOTS',templates:'entry.TEMPLATES',tb:'entry.TB',consent:'entry.CONSENT'};const q=new URLSearchParams({[e.client_id]:p.client_id,[e.app]:p.app,[e.app_ver]:p.app_version,[e.ts]:p.ts,[e.fixes]:String(p.fixes),[e.shots]:String(p.shots),[e.templates]:String(p.templates),[e.tb]:String(p.tb),[e.consent]:'true'});return base+'?'+q.toString();}
async function copyJSON(){const p=await currentPayload();try{await navigator.clipboard.writeText(JSON.stringify(p,null,2));toast('Stats JSON copied');}catch{toast('Could not copy');}}
async function shareViaForm(){if(shareCooldown)return toast('Please wait a moment…');const sentToday=await getTodayCount();if(sentToday>=DAILY_CAP)return toast('Daily share limit reached');shareCooldown=true;setTimeout(()=>shareCooldown=false,60000);const p=await currentPayload();const url=buildPrefillUrl(p);browser.tabs.create({url});await bumpTodayCount();await setLastShared(Date.now());}
document.getElementById('btn-share-form')?.addEventListener('click',shareViaForm);
document.getElementById('btn-copy-json')?.addEventListener('click',copyJSON);
getLastShared().then(updateLastShared);
(function(){const btn=document.querySelector('.tabs button[data-tab="tb"]');btn?.addEventListener('click',()=>{const now=Date.now();if(now-tbLast>30000){incCounter('tb');tbLast=now;}},true);})();